### ISSUE TITLE
 Syntax error: "(" unexpected (expecting "then")

### ISSUE THREAD

**Issue by sulthonzh** [openach/openach#1]
why i get this error when generate cert? 

`./makecerts.sh: 6: ./makecerts.sh: Syntax error: "(" unexpected (expecting "then")
`

**Comment by sbrendtro** [comment]
First, I assume you're referring to makecerts.sh on the docker-openach project (https://github.com/openach/docker-openach).  There could be a few reasons for the error:

- Outdated /bin/bash shell version (check with "/bin/bash --version").  We've tested it on Ubuntu 14.04 (bash 4.3.11) and Ubuntu 16.04 (bash 4.3.48).  We've not tested it on newer versions of bash (e.g. 4.4.x, commonly shipping with Cygwin if you're running on Windows)
- Check that /bin/bash is in fact pointing to a bash shell (You'll know by running /bin/bash --version)

If worse comes to worse, you can manually run the commands you see in makecerts.sh to generate your certs.  Let us know what versions you see and we'll investigate further.

Thanks!

**Comment by sulthonzh** [comment]
@sbrendtro now successfully, before i'm using zsh, may be only support with bash
