### ISSUE TITLE
Include a LICENSE

### ISSUE THREAD

**Issue by lacabra** [openach/openach#4]
Dear project maintainers,

Thank you 🙏for open sourcing this project, this is great! 🙌

In order for many others to use this project, they need to know under which terms they can do so, and that's where including a LICENSE in your repo is immensely helpful, as it can actually make all the difference in whether they can use or not depending on what license do you release this project under.

Could you please include and specify a license for this project?
If you need any guidance, see https://choosealicense.com/

Thanks again 🙏
Victor

**Comment by sbrendtro** [comment]
https://github.com/openach/openach/commit/0b1aca936562279e7f5d80bf98c0bfd47169f9f0 Added LICENSE
