### ISSUE TITLE
Installing on a current version of PHP

### ISSUE THREAD

**Issue by keebs** [openach/openach#5]
Anyone have any advice on installing with a current version of PHP? End of life for PHP 5.5 was back in 2016!

**Comment by sbrendtro** [comment]
The latest release of this repo (1.9.2) from June has been rolled into a docker image running Ubuntu 18.04 LTS, PHP 7.3, and Yii 1.1.22. It is available here: https://github.com/openach/docker-openach

Let us know if you have any trouble with it.
